development:
  adapter: mysql2
  database: mocals_development
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  database: mocals_test
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  adapter: mysql2
  database: mocals_production
  pool: 5
  timeout: 5000
  encoding: utf8
